version: "3.9"
services:
  app:
    container_name: app
    image: wickedbyte/talks-redis-data-structures
    build:
      context: .
    volumes:
      - ./:/app:delegated
      - composer:/root/.composer/cache:delegated
    depends_on:
      - redis-server

  redis-server:
    container_name: redis-server
    image: redis
    volumes:
      - redis:/data:delegated
    ports:
      - "${DOCKER_HOST_REDIS_PORT:-6379}:6379"

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight
    volumes:
      - redisinsight:/db:delegated
    ports:
      - "${DOCKER_HOST_REDISINSIGHT_PORT:-8001}:8001"
    depends_on:
      - redis-server

volumes:
  redis:
  redisinsight:
  composer: